{
 "title": "Distributed Task QUeue",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "worker",
    "query": {
     "query": "label_values(tasks_processed_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tasks in DLQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (reason) (increase(tasks_dlq_total{instance=~\"$worker\"}[1m]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Task Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, task_type) (rate(task_duration_seconds_bucket{instance=~\"$worker\"}[1m])))",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Total tasks processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (task_type, status) (rate(tasks_processed_total{instance=~\"$worker\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tasks_in_flight", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}